services:
  # El servidor de Consul que gestionará todo
  consul-server:
    image: hashicorp/consul:1.15
    container_name: consul-server
    restart: always
    ports:
      - "8500:8500" # Interfaz web para ver servicios activos
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0"
    networks:
      - red-gateway

  # API Gateway Standalone
  api-gateway:
    image: ga-api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - consul-server
    ports:
      - "8085:8085"
    environment:
      - SPRING_CONSUL_HOST=consul-server # Conecta con el Consul de la misma red
      - JWT_SECRET=TuClaveSecretaSuperSeguraParaElSena2026
    restart: unless-stopped
    networks:
      - red-gateway

networks:
  red-gateway:
    driver: bridge